manifest = "3e02fd44caa7be73ac1b5881078bca02487d90f4d78b4e94c5aaeff6180b7cc7"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.30.2" ]
revision = "0368528c3989e727bd67b791b31fcf415b6311ac"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.30.2" ]
revision = "e3cdd8edf43fef5fb442d3ca3f724dd0ec83152b"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.30.2" ]
revision = "924c250b1d98a8f7373831531786e15facfe4818"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.30.2" ]
revision = "110fd60fe4887cfd6a04ba25622a0b0ac2763bda"
