manifest = "3123944c9c7ca65927a3d096b7717c2bb164f7a5bf706127089179f9f77e0de1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.46.0" ]
revision = "f5014d32618a7f0475d365fda1a3a27fa0bf7936"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.46.0" ]
revision = "861bbfb9dabfd181e0644d01427d086c9f3ac996"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.46.0" ]
revision = "f5cace1ce1013c1756a5f9534a5531aec4df979a"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.46.0" ]
revision = "6b2d859a251ab6d4f4695596cc9579b4ed96791a"
