manifest = "3b92a8fbbfc960f794abe28ea6f744e90849da667ac35e3c31c91b65bad72e50"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.65.1" ]
revision = "ef899f910b922b982581c55683d22a30ed10e2ab"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.65.1" ]
revision = "dfd1a8c32d76184a8ffe83d63c3a216303dc9085"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.65.1" ]
revision = "34a98fcec1a24138c32e2a13281f8d26936e4e28"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.65.1" ]
revision = "0332a5b3d01a9b3cd31f64557a6bc76ec7724d76"
