manifest = "6facd7fa4a78f2217b34b4fd8cbd527002da6ef661d4e5a63f1a1e375be88138"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.59.0" ]
revision = "ec90e8c6b2f388644b586d11eb1a3543028fa1f5"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.59.0" ]
revision = "6019dca782a1a7b7e7e105d67216d8f824423101"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.59.0" ]
revision = "06f80557aba297b003135535cdc69de522326c50"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.59.0" ]
revision = "786cd22e9f5cea81384883b9ea5be6af2dbe322e"
